name: Auto pull request on UI branches

on:
  push:
    branches: ui/*
    
jobs:
  pullrequest:
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Make pullR
        uses: repo-sync/pull-request@v2.3
        with:
          destination_branch: "master" 
          pr_label: "ui,automerge"
          pr_assignees: "Stwissel"
          github_token: ${{secrets.UI_PUSH_TOKEN }}